apiVersion: apps/v1
kind: Deployment
metadata:
  name: binder
  namespace: godel-system
  labels:
    component: binder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binder
  template:
    metadata:
      labels:
        app: binder
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: godel
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: binder
          image: harbor.ppio.baichuan-ai.com/resourcescheduler/godel-scheduler:20240813
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/binder"]
          args:
            - "--leader-elect=false"
            - "--tracer=noop"
            - "--v=5"
            - "--config=/config/binder.config"
          resources:
            limits:
              cpu: "8"
              memory: 8G
            requests:
              cpu: "2"
              memory: 2G
          volumeMounts:
            - mountPath: /config
              name: binder-config
      volumes:
        - name: binder-config
          configMap:
            name: godel-binder-config
            items:
              - key: godel-binder-config
                path: binder.config