apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  namespace: godel-system
  labels:
    component: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godel-dispatcher
  template:
    metadata:
      labels:
        app: godel-dispatcher
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: godel
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: dispatcher
          image: harbor.ppio.baichuan-ai.com/resourcescheduler/godel-scheduler:20240813
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/dispatcher"]
          args:
            - "--leader-elect=false"
            - "--tracer=noop"
            - "--v=5"
          resources:
            limits:
              cpu: "8"
              memory: 8G
            requests:
              cpu: "2"
              memory: 2G
